### ISSUE TITLE
CVSSv3 Temporal score

### ISSUE THREAD

**Issue by luxifer** [spiegel-im-spiegel/go-cvss#1]
Hello,

Are you interested in the Temporal Score parsing and calculation? I'm asking because I have an internal fork of your repo and I needed that so i thought it would be nice to propose the patch upstream.

Regards,

**Comment by spiegel-im-spiegel** [comment]
Hi, luxifer.

Thank you for your advice.  If you give me a patch code or PR, merge it.

**Comment by luxifer** [comment]
I'll take time to subimt a PR this week.

**Comment by spiegel-im-spiegel** [comment]
many many thanks @luxifer and merged your code.
